# -*- coding: utf-8 -*-
"""Project103.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14RZWVyDY83llBQZ9O760ktRAmbJkt4Y2
"""



import pandas as pd
import plotly.express as px
df=pd.read_csv('CovidCases.csv')
fig=px.scatter(df,x='date',y='cases',color='country')
fig.show()